### ISSUE TITLE
Is it working yet?

### ISSUE THREAD

**Issue by saltmurai** [Tee-Stark/demo-mavsdk-go#1]
I couldn't get the original repo to work.

**Comment by Tee-Stark** [comment]
Hi @saltmurai yes this one works, but I did some fixes locally I might have to look at before I can confirm that this one works properly. I made this as a dummy version of the original repo so that I could make changes and test without breaking the original code.

**Comment by saltmurai** [comment]
Thanks @Tee-Stark. That's awesome. I am trying to bring the Ground Control Station to the browser and wrote Backend with Go but couldn't get the official Go repo from mavsdk to work :) So I have to resolve to using Python for mavlink connection. Definitely will try this out later. I'm thinking about doing something similar to MavSDK Python but in Go. We could colab if you are interested :).

**Comment by Tee-Stark** [comment]
That's amazing! I'll be very much interested in a collab ;).

**Comment by saltmurai** [comment]
Yupp I will make a fork
